version: "3.1"

services:

  mongodb:
    container_name: 'mongo-connect'
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: twitter
    volumes:
      - ./database:/data/db
